### ISSUE TITLE
Application built with libpng-1.5.17 but running with 1.6.13

### ISSUE THREAD

**Issue by plummerfernandez** [jcjohnson/texture-synthesis#1]
Hi I'm getting the following error, but don't know if I should try to downgrade to libpng-1.5.17 or update the app. In both cases I'm not sure how to proceed. Thanks

libpng warning: Application built with libpng-1.5.17 but running with 1.6.13
/Users/plummerfernandez/torch/install/bin/luajit: ...mmerfernandez/torch/install/share/lua/5.1/image/init.lua:148: [read_png] png_create_read_struct failed
stack traceback:
    [C]: in function 'load'
    ...mmerfernandez/torch/install/share/lua/5.1/image/init.lua:148: in function 'loader'
    ...mmerfernandez/torch/install/share/lua/5.1/image/init.lua:344: in function 'load'
    synthesis.lua:203: in main chunk
    [C]: in function 'dofile'
    ...ndez/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x01085c01c0

**Comment by plummerfernandez** [comment]
i fixed it by re-installing image:
luarocks install image

**Comment by jcjohnson** [comment]
I'm glad you figured it out!
